gfx/detail/bb_bunker/SILO2_WET1_DETAIL.tga
gfx/detail/bb_bunker/SILO2_WET4C_DETAIL.tga
gfx/detail/bb_bunker/-0SILO2_W3_DETAIL.tga
gfx/detail/bb_bunker/TNNL_SWRC1_DETAIL.tga
gfx/detail/bb_bunker/OUT_PAV3_DETAIL.tga
gfx/detail/bb_bunker/TNNL_FLR5_DETAIL.tga
gfx/detail/bb_bunker/OUT_WLK2_DETAIL.tga
gfx/detail/bb_bunker/LAB1_BLUXFLR1_DETAIL.tga
gfx/detail/bb_bunker/-0FIFTIES_C_DETAIL.tga
gfx/detail/bb_bunker/-0LAB1_W4GAD_DETAIL.tga
gfx/detail/bb_bunker/LAB1_DOOR2_DETAIL.tga
gfx/detail/bb_bunker/C1A0_LABW7B_DETAIL.tga
gfx/detail/bb_bunker/C1A0_LABGLU_DETAIL.tga
gfx/detail/bb_bunker/LAB1_DOOR7_DETAIL.tga
gfx/detail/bb_bunker/CRETE3_WALL02_DETAIL.tga
gfx/detail/bb_bunker/OUT_SNDBG5_DETAIL.tga
gfx/detail/bb_bunker/C1A3_DR1_DETAIL.tga
gfx/detail/bb_bunker/-0SILO2_P1_DETAIL.tga
gfx/detail/bb_bunker/FIFTIES_DR3D_DETAIL.tga
gfx/detail/bb_bunker/GENERIC69_DETAIL.tga
gfx/detail/bb_bunker/-1SILO2_WALL3_DETAIL.tga
gfx/detail/bb_bunker/-0TNNL_W4_DETAIL.tga
gfx/detail/bb_bunker/TNNL_W12_DETAIL.tga
gfx/detail/bb_bunker/SILO2_GAD4_DETAIL.tga
gfx/detail/bb_bunker/-1SILO2_WALL1_DETAIL.tga
gfx/detail/bb_bunker/SILO2_C1B_DETAIL.tga
gfx/detail/bb_bunker/SILO2_PAN6_DETAIL.tga
gfx/detail/bb_bunker/C1A1_GAD3_DETAIL.tga
gfx/detail/bb_bunker/C1A1_GAD4A_DETAIL.tga
gfx/detail/bb_bunker/-1OUT_W5B_DETAIL.tga
gfx/detail/bb_bunker/-0CRETE2_FLR04_DETAIL.tga
gfx/detail/bb_bunker/GENERIC101D_DETAIL.tga
gfx/detail/bb_bunker/TNNL_C1B3_DETAIL.tga
gfx/detail/bb_bunker/CRETE4_FLR01_DETAIL.tga
gfx/detail/bb_bunker/FIFTIES_CMP1C_DETAIL.tga
gfx/detail/bb_bunker/FIFTIES_CMP1B_DETAIL.tga
gfx/detail/bb_bunker/SILO2_P2_DETAIL.tga
gfx/detail/bb_bunker/GENERIC64_DETAIL.tga
gfx/detail/bb_bunker/GENERIC015A_DETAIL.tga
gfx/detail/bb_bunker/~LIGHT3E_DETAIL.tga
gfx/detail/bb_bunker/GENLOCKER_DETAIL.tga
gfx/detail/bb_bunker/FIFTIES_CMP4A_DETAIL.tga
gfx/detail/bb_bunker/DRKMTL_SCRN4_DETAIL.tga
gfx/detail/bb_bunker/C1A1_GAD4_DETAIL.tga
gfx/detail/bb_bunker/OUT_BOX2_DETAIL.tga
gfx/detail/bb_bunker/OUT_BOX2B_DETAIL.tga
gfx/detail/bb_bunker/OUT_BOX2C_DETAIL.tga
gfx/detail/bb_bunker/OUT_BOX2D_DETAIL.tga
gfx/detail/bb_bunker/TNNL_W14B_DETAIL.tga
gfx/detail/bb_bunker/SILO2_WETDR_DETAIL.tga
gfx/detail/bb_bunker/GENERIC009_DETAIL.tga
gfx/detail/bb_bunker/-3SILO2_P2B_DETAIL.tga
gfx/detail/bb_bunker/TNNL_W4A_DETAIL.tga
gfx/detail/bb_bunker/FIFTSFILE1_DETAIL.tga
gfx/detail/bb_bunker/FIFTSFILE2_DETAIL.tga
gfx/detail/bb_bunker/LAB3_C2_DETAIL.tga
gfx/detail/bb_bunker/-2LAB3_FLR1B_DETAIL.tga
gfx/detail/bb_bunker/LAB3_W7_DETAIL.tga

gfx/detail/bb_reactor/LAB1_PANELG_DETAIL.tga
gfx/detail/bb_reactor/LAB1_W4B_DETAIL.tga
gfx/detail/bb_reactor/LAB1_PANELG_DETAIL.tga
gfx/detail/bb_reactor/LAB1_C4D2_DETAIL.tga
gfx/detail/bb_reactor/LAB1_W3_DETAIL.tga
gfx/detail/bb_reactor/LAB1_PANEL1C_DETAIL.tga
gfx/detail/bb_reactor/LAB1_PANELH_DETAIL.tga
gfx/detail/bb_reactor/LAB1_PANEL2_DETAIL.tga
gfx/detail/bb_reactor/LAB1_PANELB_DETAIL.tga
gfx/detail/bb_reactor/LAB1_PANELE_DETAIL.tga
gfx/detail/bb_reactor/LAB1_PANELC_DETAIL.tga
gfx/detail/bb_bunker/LAB1_DOOR2_DETAIL.tga
gfx/detail/bb_reactor/FIFTIES_CMP5_DETAIL.tga
gfx/detail/bb_reactor/FIFTIES_WALL6C_DETAIL.tga
gfx/detail/bb_reactor/C3A2B_REAC1_DETAIL.tga
gfx/detail/bb_reactor/C3A2B_REAC2B_DETAIL.tga
gfx/detail/bb_reactor/C3A2B_REAC2D_DETAIL.tga
gfx/detail/bb_reactor/C3A2B_REAC1B_DETAIL.tga
gfx/detail/bb_reactor/C3A2B_REAC2C_DETAIL.tga
gfx/detail/bb_reactor/C3A2B_REAC_DETAIL.tga
gfx/detail/bb_reactor/CA1X_C1A_DETAIL.tga
gfx/detail/bb_reactor/CA1X_C1B_DETAIL.tga
gfx/detail/bb_reactor/CA1X_C1C_DETAIL.tga
gfx/detail/bb_reactor/CA1X_C1D_DETAIL.tga
gfx/detail/bb_reactor/LAB1_DOOR1_DETAIL.tga
gfx/detail/bb_reactor/-0OUT_GRND2B_DETAIL.tga
gfx/detail/bb_reactor/GRATESTEP2_DETAIL.tga
gfx/detail/bb_reactor/{RAIL3_DETAIL.tga
gfx/detail/bb_reactor/C3A2B_REAC1D_DETAIL.tga
gfx/detail/bb_reactor/OUT_WALL6G_DETAIL.tga
gfx/detail/bb_reactor/OUT_WALL10_DETAIL.tga
gfx/detail/bb_reactor/{FENCE_DETAIL.tga
gfx/detail/bb_reactor/C2A2_DR_DETAIL.tga
gfx/detail/bb_reactor/XCRATE9A_DETAIL.tga
gfx/detail/bb_reactor/FIFTIES_WALL6B_DETAIL.tga
gfx/detail/bb_reactor/LAB1_DOOR01_DETAIL.tga
gfx/detail/bb_reactor/LAB1_W1H_DETAIL.tga
gfx/detail/bb_reactor/LAB1_PANELA_DETAIL.tga
gfx/detail/bb_reactor/LAB1_DR5B_DETAIL.tga
gfx/detail/bb_reactor/LAB1_BRD3_DETAIL.tga
gfx/detail/bb_reactor/{GRID1_DETAIL.tga
gfx/detail/bb_reactor/OUT_W1A_DETAIL.tga
gfx/detail/bb_reactor/C1A1_CRATE2_DETAIL.tga
gfx/detail/bb_reactor/C3A1_CRATE3_DETAIL.tga
gfx/detail/bb_reactor/OUT_W1DR1_DETAIL.tga
gfx/detail/bb_reactor/XCRATE11B_DETAIL.tga

maps/bb_reactor_detail.txt
maps/bb_reactor.tsk